"""Toolkit-independent helpers for rendering and executing argparse command trees."""

from __future__ import annotations

import argparse
import contextlib
import io
from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Sequence


class ArgumentValidationError(ValueError):
    """Raised when argv generated by the UI is rejected by argparse."""


@dataclass(frozen=True)
class ArgumentField:
    """An argparse action together with its location in a command tree."""

    path: tuple[str, ...]
    action: argparse.Action

    @property
    def key(self) -> tuple[tuple[str, ...], str]:
        return self.path, self.action.dest

    @property
    def required(self) -> bool:
        return bool(self.action.required) or (
            not self.action.option_strings and self.action.nargs not in ("?", "*")
        )

    @property
    def is_boolean(self) -> bool:
        return isinstance(
            self.action, (argparse._StoreTrueAction, argparse._StoreFalseAction)
        )

    @property
    def is_list(self) -> bool:
        return self.action.nargs not in (None, "?") and not self.is_boolean

    @property
    def fixed_length(self) -> int | None:
        """Return the required item count for a fixed-size argparse sequence."""
        return self.action.nargs if isinstance(self.action.nargs, int) else None

    @property
    def item_labels(self) -> tuple[str, ...]:
        """Return labels from argparse metavar metadata for fixed-size sequences."""
        if self.fixed_length is None:
            return ()
        metavar = self.action.metavar
        if isinstance(metavar, tuple):
            return tuple(str(item).replace("_", " ").title() for item in metavar)
        if isinstance(metavar, str):
            return tuple(f"{metavar} {index + 1}" for index in range(self.fixed_length))
        return tuple(f"Value {index + 1}" for index in range(self.fixed_length))

    @property
    def is_path_like(self) -> bool:
        """Whether the action is likely to accept a filesystem path."""
        dest = self.action.dest.lower()
        help_text = (self.action.help or "").lower()
        path_names = {
            "path",
            "paths",
            "data",
            "dataset",
            "dataset_path",
            "data_paths",
            "checkpoint",
            "checkpoints",
            "imgpath",
            "output",
            "output_path",
            "outputpath",
            "out",
            "label_file",
            "queue_file",
            "bag_path",
            "result_folders",
        }
        return (
            dest in path_names
            or dest.endswith(("_path", "_paths", "_file", "_files", "_dir"))
            or any(word in help_text for word in ("path", "file", "folder", "directory"))
        )


def subparser_action(parser: argparse.ArgumentParser) -> argparse.Action | None:
    """Return the parser's single subparser action, if it has one."""
    return next(
        (
            action
            for action in parser._actions
            if isinstance(action, argparse._SubParsersAction)
        ),
        None,
    )


def command_choices(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """Return immediate subcommand names and their parsers."""
    action = subparser_action(parser)
    return {} if action is None else dict(action.choices)


def resolve_parser(
    root: argparse.ArgumentParser, path: Sequence[str]
) -> argparse.ArgumentParser:
    """Resolve a selected subcommand path, rejecting invalid selections."""
    parser = root
    for command in path:
        choices = command_choices(parser)
        if command not in choices:
            raise ArgumentValidationError(
                f"'{command}' is not a subcommand of '{parser.prog}'."
            )
        parser = choices[command]
    return parser


def parser_chain(
    root: argparse.ArgumentParser, path: Sequence[str]
) -> list[tuple[tuple[str, ...], argparse.ArgumentParser]]:
    """Return the root and every parser chosen by *path*."""
    parser = root
    chain = [((), parser)]
    selected: tuple[str, ...] = ()
    for command in path:
        parser = resolve_parser(parser, (command,))
        selected += (command,)
        chain.append((selected, parser))
    return chain


def fields_for_path(
    root: argparse.ArgumentParser, path: Sequence[str]
) -> list[ArgumentField]:
    """Return renderable actions from the selected parser chain."""
    fields: list[ArgumentField] = []
    for parser_path, parser in parser_chain(root, path):
        for action in parser._actions:
            if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):
                continue
            fields.append(ArgumentField(parser_path, action))
    return fields


def default_value(field: ArgumentField) -> Any:
    """Provide the editable default represented by an argparse action."""
    return field.action.default


def build_argv(
    root: argparse.ArgumentParser,
    path: Sequence[str],
    values: Mapping[tuple[tuple[str, ...], str], Any],
) -> list[str]:
    """Build CLI tokens from dynamic form values without shell parsing or quoting."""
    fields = fields_for_path(root, path)
    argv: list[str] = []
    fields_by_path: dict[tuple[str, ...], list[ArgumentField]] = {}
    for field in fields:
        fields_by_path.setdefault(field.path, []).append(field)

    for depth in range(len(path) + 1):
        current_path = tuple(path[:depth])
        for field in fields_by_path.get(current_path, []):
            value = values.get(field.key, default_value(field))
            _append_action(argv, field, value)
        if depth < len(path):
            argv.append(path[depth])
    return argv


def validate_argv(parser: argparse.ArgumentParser, argv: Sequence[str]) -> argparse.Namespace:
    """Parse UI argv and turn argparse's user-facing exit into a validation error."""
    stderr = io.StringIO()
    try:
        with contextlib.redirect_stderr(stderr):
            return parser.parse_args(list(argv))
    except SystemExit as exc:
        message = stderr.getvalue().strip()
        raise ArgumentValidationError(message or "Invalid command arguments.") from exc


def _append_action(argv: list[str], field: ArgumentField, value: Any) -> None:
    action = field.action
    if field.is_boolean:
        if bool(value) != bool(action.default):
            argv.append(_option_token(action))
        return

    if field.is_list:
        normalized = _normalize_list(value)
        if not normalized:
            if field.required:
                raise ArgumentValidationError(f"'{action.dest}' requires at least one value.")
            return
        if action.option_strings:
            if normalized != _normalize_list(action.default):
                argv.extend([_option_token(action), *normalized])
        else:
            argv.extend(normalized)
        return

    normalized = "" if value is None else str(value)
    if not normalized:
        if field.required:
            raise ArgumentValidationError(f"'{action.dest}' is required.")
        return
    if action.option_strings:
        if normalized != str(action.default):
            argv.extend([_option_token(action), normalized])
    else:
        argv.append(normalized)


def _normalize_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [line.strip() for line in value.splitlines() if line.strip()]
    if isinstance(value, Iterable):
        return [str(item) for item in value]
    return [str(value)]


def _option_token(action: argparse.Action) -> str:
    return next(
        (option for option in action.option_strings if option.startswith("--")),
        action.option_strings[0],
    )
